# ---------- defaults ----------
defaults:

  time_anchors:
    timezone: "America/Chicago"
    wake: "05:25"
    sleep: "22:00"
    meals:
      breakfast: "07:00–07:30"
      lunch: "12:00–13:00"
      dinner: "18:30–19:30"
    reading_block: "05:25–06:00"
    evening_wrap: "21:30"
    wind_down_buffer: 30  # minutes

  block_parameters:
    default_length: 90
    min_length: 30
    transition_buffer: 15
    types:
      deep:
        length: 90
        transition_after: 15
      admin:
        length: 45
        transition_after: 10
      personal:
        length: 30
        transition_after: 10

  focus_profiles:
    weekday:
      morning: "deep"
      midday: "admin"
      afternoon: "flex"
      evening: "personal"
    weekend:
      morning: "personal"
      midday: "flex"
      evening: "admin"

  activities:
    ride:
      duration: 60
      cooldown: 10
      preferred_time: "morning"
      earliest_start: "07:15"
    gym:
      duration: 75
      cooldown: 15
      preferred_time: "afternoon"
      post_therapy_priority: true
    walk:
      default_after_meals: true
    recovery:
      include: true
      preferred_time: "evening"

  locations:
    home:
      commute: 0
    guild_row:
      commute: 30
      prep_buffer: 10

  idle_time:
    allow: true
    strategies:
      - "suggest journaling"
      - "schedule admin"
      - "prompt reflection"
    idle_window_cap: 45
    minimum_rest_ratio: 0.15

  preferences:
    morning_person: true
    prefers_ride_morning: true
    prefers_gym_afternoon: true
    default_recovery_ratio: 0.15
    preferred_pacing: "balanced"
    reflection_required: true

  ui_options:
    scaffold_format: "hourly"
    include_context_summary: true
    include_timecode_in_log: true
    log_format: "markdown"
    verbosity: "medium"
    daily_log_header: "Echo: Today’s Scaffold"

# ---------- weekly_schedule ----------
weekly_schedule:

  monday:
    location: guild_row
    anchors:
      - time: "08:00–08:15"
        task: "Meeting with P. Lewis"
        recurrence: "weekly"
        first_occurrence: "2025-06-16"
    notes: []

  tuesday:
    location: guild_row
    anchors:
      - time: "15:00–16:00"
        task: "Meeting with F. Cotrufo"
        recurrence: "biweekly"
        first_occurrence: "2025-06-17"
    notes:
      - "Make sure to schedule 40–60 minutes of meeting prep before any meeting with F. Cotrufo"

  wednesday:
    location: home
    anchors:
      - time: "15:00–16:00"
        task: "Therapy with K. Jasko"
        recurrence: "weekly"
        first_occurrence: "2025-06-18"
    notes:
      - "Therapy downtown -- need to plan how to get there and back."

  thursday:
    location: guild_row
    anchors:
      - time: "10:00–11:45"
        task: "Coworking with P. Hansen, E. Patterson, and A. Prairie"
        recurrence: "weekly"
        first_occurrence: "2025-06-19"
    notes: []

  friday:
    location: guild_row
    anchors: []
    notes:
      - "Default to admin or finishing touches"
      - "Monthly sync last Friday of month"

  saturday:
    location: home
    anchors: []
    notes: []

  sunday:
    location: home
    anchors:
      - time: "08:30–09:15"
        task: "Plan meals for the week"
        recurrence: "weekly"
        first_occurrence: "2025-06-15"
      - time: "10:00–13:00"
        task: "Walk with H. Howe"
        recurrence: "weekly"
        first_occurrence: "2025-06-15"
      - time: "20:00–21:00"
        task: "Sunday Sync"
        recurrence: "weekly"
        first_occurrence: "2025-06-15"
    notes: []

# ---------- profiles ----------
profiles:
  travel:
    overrides:
      time_anchors:
        wake: "06:30"  # later wake time while traveling
