# ==============================================================================
# CANONICAL TEST FIXTURE
#
# This file is the single source of truth for test data. It is designed to
# test the core functionality of the config loader and validators.
# ==============================================================================

defaults:
  timezone: "America/Chicago"
  wake_time: "06:00"
  sleep_time: "22:00"

# ------------------------------------------------------------------------------

weekly_schedule:
  # A standard day with a fixed event.
  monday:
    anchors:
      - time: "06:00–06:30"
        task: "Morning Reading"
    fixed:
      - time: "12:00–12:30"
        label: "Team Standup"
        source: "gcal"

  # A day with no fixed events, to test flexibility.
  tuesday:
    anchors:
      - time: "06:00–06:30"
        task: "Morning Reading"

  # A day to test overlaps and validation.
  wednesday:
    anchors: []
    fixed: []

# ------------------------------------------------------------------------------

projects:
  # A fully-featured active project with a deadline and milestones.
  echo_dev:
    name: "Echo Development"
    status: "active"
    current_focus: "Refactor the test suite to be robust and comprehensive."
    deadline: "2025-07-31"
    milestones:
      - description: "Complete core module refactoring"
        due_date: "2025-07-15"
      - description: "Implement 'The Archivist' (logging)"
        due_date: "2025-07-22"

  # An on-hold project that should be ignored by some parts of the system.
  grant_proposal:
    name: "NIH Grant Proposal"
    status: "on_hold"
    current_focus: "Waiting for feedback from collaborators."

# ------------------------------------------------------------------------------

profiles:
  # A simple profile for testing overrides.
  travel:
    overrides:
      defaults:
        wake_time: "08:00"

# Email Integration Settings
email:
  # IMAP Configuration (Universal - works with any email provider)
  imap:
    provider: "outlook"  # Options: outlook, gmail, yahoo, icloud
    server: "outlook.office365.com"  # Auto-filled based on provider
    port: 993
    username: "your-email@university.edu"
    password: "your-app-password"  # Use app password for security
    use_ssl: true
  
  # Email Processing Settings
  important_senders:
    - "ceo@company.com"
    - "manager@company.com"
    - "client@company.com"
    - "professor@university.edu"
    - "advisor@university.edu"
  
  urgent_keywords:
    - "urgent"
    - "asap"
    - "deadline"
    - "important"
    - "critical"
    - "emergency"
    - "immediate"
  
  action_keywords:
    - "please"
    - "can you"
    - "need"
    - "review"
    - "send"
    - "schedule"
    - "meeting"
    - "respond"
    - "reply"
    - "follow up"
