# Echo User Configuration
# This file defines your personal schedule, projects, and preferences.

defaults:
  wake_time: "06:00"
  sleep_time: "22:00"
  timezone: "America/Chicago"

# User-defined categories for time tracking
categories:
  mappings:
    # Override defaults or add new mappings
    "Echo": "Development"
    "Work": "Development"
    "Client Work": "Client Work"
    "Learning": "Learning"
    "Health": "Health"
    "Admin": "Admin"

weekly_schedule:
  monday:
    anchors:
      - time: "06:00-07:00"
        task: "Morning Routine"
        meta:
          note: "Start the day with intention"
    fixed: []

  tuesday:
    anchors:
      - time: "06:00-07:00"
        task: "Morning Routine"
    fixed: []

  wednesday:
    anchors:
      - time: "06:00-07:00"
        task: "Morning Routine"
    fixed: []

  thursday:
    anchors:
      - time: "06:00-07:00"
        task: "Morning Routine"
    fixed: []

  friday:
    anchors:
      - time: "06:00-07:00"
        task: "Morning Routine"
    fixed: []

  saturday:
    anchors:
      - time: "08:00-09:00"
        task: "Weekend Reading"
      - time: "19:00-21:00"
        task: "Dinner with Friends"
    fixed: []

  sunday:
    anchors:
      - time: "08:00-09:00"
        task: "Weekend Reading"
      - time: "19:00-21:00"
        task: "Dinner with Friends"
    fixed: []

projects:
  echo:
    name: "Echo Development"
    status: "active"
    current_focus: "Build the new 'Work Session' feature"
    deadline: "2025-07-31"
    milestones:
      - description: "Complete prompt engine refactor"
        due_date: "2025-07-20"
      - description: "Implement analytics dashboard"
        due_date: "2025-07-25"
      - description: "Add project tracking features"
        due_date: "2025-07-31"

profiles:
  travel:
    name: "Travel Mode"
    overrides:
      wake_time: "07:00"
      sleep_time: "23:00"
  sick:
    name: "Sick Day"
    overrides:
      wake_time: "08:00"
      sleep_time: "21:00"