defaults:
  wake_time: 07:00
  sleep_time: '22:00'
weekly_schedule:
  monday:
    anchors:
    - time: "09:00\u201310:00"
      category: personal
      task: Test Block
      description: Test description
    fixed: []
    flex: []
  tuesday:
    anchors:
    - time: "09:00\u201310:00"
      category: personal
      task: Test Block
      description: Test description
    fixed: []
    flex: []
  wednesday:
    anchors: []
    fixed: []
    flex: []
  thursday:
    anchors: []
    fixed: []
    flex: []
  friday:
    anchors: []
    fixed: []
    flex: []
  saturday:
    anchors: []
    fixed: []
    flex: []
  sunday:
    anchors: []
    fixed: []
    flex: []
projects:
  echo:
    name: Echo Development
    status: active
    current_focus: Email integration testing
  personal:
    name: Personal Projects
    status: active
    current_focus: General productivity
profiles:
  default:
    name: Default Profile
    overrides: {}
email:
  graph_api:
    client_id: ${ECHO_GRAPH_CLIENT_ID}
    client_secret: ${ECHO_GRAPH_CLIENT_SECRET}
    redirect_uri: ${ECHO_GRAPH_REDIRECT_URI}
    scopes:
    - Mail.Read
    - Mail.ReadWrite
    - User.Read
  important_senders:
  - ceo@company.com
  - manager@company.com
  - client@company.com
  - professor@colostate.edu
  - advisor@colostate.edu
  - sam.leuthold@colostate.edu
  - samleuthold@colostate.edu
  urgent_keywords:
  - urgent
  - asap
  - deadline
  - important
  - critical
  - emergency
  - immediate
  action_keywords:
  - please
  - can you
  - need
  - review
  - send
  - schedule
  - meeting
  - respond
  - reply
  - follow up
  - accepted
  - presentation
  - expire
  - token
