defaults:
  wake_time: 07:00
  sleep_time: '22:00'
weekly_schedule:
  monday:
    anchors:
    - time: "05:30\u201306:00"
      category: personal
      task: Morning Reading
      description: 'I like to start the day by reading some non-fiction for about
        30 minutes. '
    - time: "07:10\u201307:40"
      category: meals
      task: Breakfast
      description: 'I eat for about 30 minutes most morning, and also make smoothies
        for my wife and I. '
    - time: "07:40\u201308:15"
      category: personal
      task: Morning Routine
      description: 'This is when I shower, get dressed, etc. Usually it doesn''t take
        too long. '
    - time: "16:15\u201316:30"
      category: personal
      task: Commute to the Gym
      description: Ride my bike to Midtown Fitness
    - time: "08:15\u201308:45"
      category: personal
      task: Commute to Guild Row
      description: 'Riding my bike to work. '
    - time: "16:30\u201317:45"
      category: exercise
      task: Strength Training
      description: Trying to get big and strong dawg.
    fixed: []
    flex:
    - time: "12:30\u201313:00"
      category: meals
      task: Lunch
  tuesday:
    anchors:
    - time: "05:30\u201306:00"
      category: personal
      task: Morning Reading
      description: 'I like to start the day by reading some non-fiction for about
        30 minutes. '
    - time: "07:10\u201307:40"
      category: meals
      task: Breakfast
      description: 'I eat for about 30 minutes most morning, and also make smoothies
        for my wife and I. '
    - time: "07:40\u201308:15"
      category: personal
      task: Morning Routine
      description: 'This is when I shower, get dressed, etc. Usually it doesn''t take
        too long. '
    - time: "16:15\u201316:30"
      category: personal
      task: Commute to the Gym
      description: Ride my bike to Midtown Fitness
    - time: "08:15\u201308:45"
      category: personal
      task: Commute to Guild Row
      description: 'Riding my bike to work. '
    - time: "16:30\u201317:45"
      category: exercise
      task: Strength Training
      description: Trying to get big and strong dawg.
    fixed: []
    flex:
    - time: "12:30\u201313:00"
      category: meals
      task: Lunch
  wednesday:
    anchors:
    - time: "05:30\u201306:00"
      category: personal
      task: Morning Reading
      description: 'I like to start the day by reading some non-fiction for about
        30 minutes. '
    - time: "07:10\u201307:40"
      category: meals
      task: Breakfast
      description: 'I eat for about 30 minutes most morning, and also make smoothies
        for my wife and I. '
    - time: "07:40\u201308:15"
      category: personal
      task: Morning Routine
      description: 'This is when I shower, get dressed, etc. Usually it doesn''t take
        too long. '
    - time: "16:15\u201316:30"
      category: personal
      task: Commute to the Gym
      description: Ride my bike to Midtown Fitness
    - time: "08:15\u201308:45"
      category: personal
      task: Commute to Guild Row
      description: 'Riding my bike to work. '
    - time: "16:30\u201317:45"
      category: exercise
      task: Strength Training
      description: Trying to get big and strong dawg.
    fixed: []
    flex:
    - time: "12:30\u201313:00"
      category: meals
      task: Lunch
  thursday:
    anchors:
    - time: "05:30\u201306:00"
      category: personal
      task: Morning Reading
      description: 'I like to start the day by reading some non-fiction for about
        30 minutes. '
    - time: "07:10\u201307:40"
      category: meals
      task: Breakfast
      description: 'I eat for about 30 minutes most morning, and also make smoothies
        for my wife and I. '
    - time: "07:40\u201308:15"
      category: personal
      task: Morning Routine
      description: 'This is when I shower, get dressed, etc. Usually it doesn''t take
        too long. '
    - time: "16:15\u201316:30"
      category: personal
      task: Commute to the Gym
      description: Ride my bike to Midtown Fitness
    - time: "08:15\u201308:45"
      category: personal
      task: Commute to Guild Row
      description: 'Riding my bike to work. '
    - time: "16:30\u201317:45"
      category: exercise
      task: Strength Training
      description: Trying to get big and strong dawg.
    fixed: []
    flex:
    - time: "12:30\u201313:00"
      category: meals
      task: Lunch
  friday:
    anchors:
    - time: "05:30\u201306:00"
      category: personal
      task: Morning Reading
      description: 'I like to start the day by reading some non-fiction for about
        30 minutes. '
    - time: "07:10\u201307:40"
      category: meals
      task: Breakfast
      description: 'I eat for about 30 minutes most morning, and also make smoothies
        for my wife and I. '
    - time: "07:40\u201308:15"
      category: personal
      task: Morning Routine
      description: 'This is when I shower, get dressed, etc. Usually it doesn''t take
        too long. '
    - time: "16:15\u201316:30"
      category: personal
      task: Commute to the Gym
      description: Ride my bike to Midtown Fitness
    - time: "08:15\u201308:45"
      category: personal
      task: Commute to Guild Row
      description: 'Riding my bike to work. '
    - time: "16:30\u201317:45"
      category: exercise
      task: Strength Training
      description: Trying to get big and strong dawg.
    fixed: []
    flex:
    - time: "12:30\u201313:00"
      category: meals
      task: Lunch
  saturday:
    anchors: []
    fixed: []
    flex: []
  sunday:
    anchors: []
    fixed: []
    flex: []
projects:
  echo:
    name: Echo Development
    status: active
    current_focus: Email integration testing
  personal:
    name: Personal Projects
    status: active
    current_focus: General productivity
profiles:
  default:
    name: Default Profile
    overrides: {}
email:
  graph_api:
    client_id: ${ECHO_GRAPH_CLIENT_ID}
    client_secret: ${ECHO_GRAPH_CLIENT_SECRET}
    redirect_uri: ${ECHO_GRAPH_REDIRECT_URI}
    scopes:
    - Mail.Read
    - Mail.ReadWrite
    - User.Read
  important_senders:
  - ceo@company.com
  - manager@company.com
  - client@company.com
  - professor@colostate.edu
  - advisor@colostate.edu
  - sam.leuthold@colostate.edu
  - samleuthold@colostate.edu
  urgent_keywords:
  - urgent
  - asap
  - deadline
  - important
  - critical
  - emergency
  - immediate
  action_keywords:
  - please
  - can you
  - need
  - review
  - send
  - schedule
  - meeting
  - respond
  - reply
  - follow up
  - accepted
  - presentation
  - expire
  - token
