name: Lint and Validate Config

on:
  push:
    paths:
      - "config/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "config/**"
      - ".github/workflows/**"

jobs:
  config-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install ruamel.yaml

      - name: Run config key order check
        run: python scripts/lint_config.py
